In [1]:
import pandas as pd

In [2]:
# data from 2011 - 2016, 2018-2020 with missing data
df = pd.read_csv('raw_data.csv', header=None)

In [3]:
# complement to missing data
ab_complement = pd.read_csv('missing_11_18.csv')

In [4]:
# complete data for 2014, 2016, 2017, 2019, 2020
ab_14_16_17 = pd.read_csv('abortion-incidence-service-availability-us-2017-tables.csv')
ab_19_20 = pd.read_csv('Copy of abortion_provider_census_2020_topline.csv')

In [5]:
ab_complement.head()

           state     11     12     13     15     18
0     California  22.99  21.62  20.59  18.50  17.61
1  New Hampshire  12.90  11.11   9.46   9.90   8.80
2       Maryland  28.76  26.48  24.63  24.43  25.34
3        Wyoming   1.13   1.20   1.28   1.00   1.12

In [6]:
# change ab_complement column names
ab_complement.columns = ['state', 2011, 2012, 2013, 2015, 2018]

In [7]:
# change df column names
col = ['state']
col.extend(range(2011,2017))
col.extend(range(2018,2021))
df.columns = col

In [8]:
# from df, only select the years without complete data, which are 2011-2013, 2015, 2018
ab_rest_years = df.drop(columns=[2014, 2016, 2019, 2020])

In [9]:
# drop missing states
ab_rest_years = ab_rest_years[~ab_rest_years['state'].isin(['California', 'Maryland', 'New Hampshire', 'Wyoming'])]

In [10]:
# add complement data 
ab_rest_years = pd.concat([ab_rest_years, ab_complement]).reset_index(drop=True)

In [11]:
# clean ab_14_16_17
ab_14_16_17.head()

  Region and state  2014  2016  2017  Unnamed: 4
0      Connecticut  19.2  18.1  17.7         NaN
1            Maine   9.5   8.9   8.8         NaN
2    Massachusetts  15.3  14.0  13.5         NaN
3    New Hampshire  10.4   9.6   9.2         NaN
4       New Jersey  25.8  28.2  28.0         NaN

In [12]:
# change ab_14_16_17 column names
ab_14_16_17.rename(columns={'Region and state': 'state'}, inplace=True)

In [13]:
# drop null col
ab_14_16_17 = ab_14_16_17.drop(ab_14_16_17.columns[4], axis=1)

In [14]:
ab_rate = pd.merge(ab_14_16_17, ab_19_20, on='state')
ab_rate = pd.merge(ab_rate, ab_rest_years, on='state')

In [15]:
ab_rate

,state,2014,2016,2017,2019,2020,2011,2012,2013,2015,2018
0,Connecticut,19.2,18.1,17.7,17.9,16.7,18.4,17.4,15.4,14.6,13.9
1,Maine,9.5,8.9,8.8,9.0,10.1,7.4,4.2,8.3,7.9,8.4
2,Massachusetts,15.3,14.0,13.5,13.6,12.2,15.4,14.8,14.3,13.5,13.1
3,New Hampshire,10.4,9.6,9.2,8.5,8.3,12.9,11.11,9.46,9.9,8.8
4,New Jersey,25.8,28.2,28.0,28.8,29.2,15.4,13.3,12.6,13.4,13.6
5,New York,29.6,27.6,26.3,30.2,28.8,27.6,25.8,24.3,23.1,19.8
6,Pennsylvania,13.3,13.5,13.1,13.1,13.6,14.9,14.2,13.3,13.3,12.7
7,Rhode Island,17.0,16.8,16.7,13.6,13.3,19.6,16.8,15.5,12.6,13.5
8,Vermont,12.1,12.0,11.4,10.4,10.7,11.5,10.9,10.5,10.9,10.5
9,Illinois,16.3,16.4,16.6,20.9,21.3,15.8,16.5,15.7,15.5,16.9
10,Indiana,6.3,5.9,5.9,5.9,6.0,7.1,6.8,6.3,6.1,6.2
11,Iowa,7.5,7.2,6.3,5.8,5.9,8.3,8,7.6,6.8,4.8
12,Kansas,12.9,12.2,12.2,12.0,14.5,14,13.4,13.3,12.4,12.4
13,Michigan,15.4,14.6,14.2,15.5,16.8,12.3,12.2,13.8,14.4,14.2
14,Minnesota,9.3,9.6,10.1,10.3,10.2,10.6,10.2,9.4,9.4,9.2
15,Missouri,4.4,4.5,4.0,1.3,0.1,4.9,4.8,4.6,4,2.5
16,Nebraska,6.3,5.3,5.5,5.8,5.9,6.6,6.4,6,5.5,5.6
17,North Dakota,8.7,7.9,7.9,7.5,7.8,9.5,9.8,8.4,7.9,7.7
18,Ohio,10.3,9.3,9.4,9.2,9.5,11.2,11.5,10.5,9.5,9.2
19,South Dakota,3.5,3.0,3.1,2.5,0.8,3.9,4.1,3.8,2.8,2.4
20,Wisconsin,5.6,5.7,5.9,6.6,6.4,6.6,6.4,5.9,5.2,5.7
21,Alabama,8.3,7.0,6.4,6.2,6.0,9.9,9.5,8.8,6.2,6.8
22,Arkansas,8.0,5.7,5.5,5.0,5.6,7.1,6.6,6.5,6.5,5.3
23,Delaware,16.7,12.5,10.5,11.3,10.0,21.2,21.3,16.9,15.4,9.7
24,District of Columbia,32.7,10.4,30.2,51.8,48.9,16.7,15.4,14.7,7,25.3
25,Florida,20.6,18.5,18.6,18.5,19.7,21.6,21.1,20,19.3,18.1
26,Georgia,15.7,16.4,16.9,18.3,18.9,15.8,15,14.7,14.6,15.7
27,Kentucky,4.1,3.9,3.8,4.3,4.8,4.6,4.5,4.3,3.7,3.8
28,Louisiana,10.8,11.2,10.6,8.8,8.0,9.6,9.9,10.6,9.9,8.7
29,Maryland,23.4,25.3,25.0,25.3,25.9,28.76,26.48,24.63,24.43,25.34
30,Mississippi,3.8,4.2,4.3,5.5,6.1,3.7,3.6,3.6,4.4,5.1
31,North Carolina,15.1,13.5,14.6,14.2,15.3,13.4,12.4,11.6,13.9,13.5
32,Oklahoma,7.0,5.7,6.2,11.7,12.4,7.3,6.9,6.6,6.1,6.5
33,South Carolina,6.4,6.0,5.3,5.1,5.3,6.9,6.5,6.3,6.1,4.8
34,Tennessee,10.7,9.2,9.2,7.5,8.1,12.6,12.4,11,8.8,8.2
35,Texas,9.8,9.2,9.4,9.8,9.5,13.4,12.5,11.4,9.4,9.2
36,Virginia,12.5,11.7,10.2,9.7,11.0,15.3,13.7,12.4,11.1,9.8
37,West Virginia,6.0,5.2,4.4,3.7,3.1,5.4,5.4,5.5,4.5,4.7
38,Alaska,10.0,8.6,8.6,9.1,8.6,11.2,11.1,9.9,9.1,8.8
39,Arizona,9.8,10.0,9.2,9.3,9.3,11.3,10.4,10.4,9.6,9
40,California,19.5,17.4,16.4,18.7,19.2,22.99,21.62,20.59,18.5,17.61
41,Colorado,12.1,11.1,10.9,10.5,11.2,10.1,9.5,9.6,9.1,7.7
42,Hawaii,14.0,11.6,12.0,12.1,12.1,10.1,10.7,7.4,7.6,8
43,Idaho,4.2,3.9,3.9,4.4,4.8,4.7,4.7,4.4,4,3.7
44,Montana,9.1,8.7,8.3,8.2,8.2,11.9,11.2,10,8.6,8.7
45,Nevada,19.4,16.5,16.4,16.4,17.9,13.1,13,10.9,12.4,14.8
46,New Mexico,11.7,13.5,11.7,11.2,14.7,10.2,8.8,10.5,11.8,9.7
47,Oregon,12.0,12.3,11.9,11.0,10.3,12.6,11.8,10.8,10.9,10.6
48,Utah,4.6,4.6,4.4,4.3,4.4,5.5,5.3,4.9,4.9,4.5
49,Washington,13.7,12.1,12.1,12.2,11.7,14.8,13.4,12.7,12.1,11.5
50,Wyoming,1.1,1.0,1.3,0.8,0.9,1.13,1.2,1.28,1.0,1.12

In [16]:
# convert dataframe to the form where year is a column
ab_rate = ab_rate.melt(id_vars=['state'], var_name='year', value_name='ab_rate')

In [17]:
# drop DC rows
ab_rate = ab_rate[ab_rate['state']!='District of Columbia']

In [18]:
ab_rate['ab_rate'] = ab_rate['ab_rate'].astype(float)

In [19]:
ab_rate.to_csv(r'..\..\cleaned_data\ab_rate.csv', index=False)